### ISSUE TITLE
TypeError: Cannot destructure property 'firstElementChild' of 't' as it is null

### ISSUE THREAD

**Issue by masx200** [WebReflection/linkedom#157]
```
TypeError: Cannot destructure property 'firstElementChild' of 't' as it is null.
at Dt.get head [as head] (https://esm.sh/v92/linkedom@0.14.12/es2015/linkedom.js:3:30275)
at Dt.get body [as body] (https://esm.sh/v92/linkedom@0.14.12/es2015/linkedom.js:3:30378)
at test (file:///sdcard/test/test.html:14:23)
at file:///sdcard/test/test.html:18:26
```

```html
<html>
<head>
<script type="module">



import { parseHTML } from "https://esm.sh/linkedom@0.14.12/";
 function JSDOM(html) {
    return parseHTML(html);
}

function test(){
const document = JSDOM(``).window.document;
const body = document.body;
return body
}
try{
	document.body.innerText=test()
}catch(e){
document.body.innerText=e.stack

}
</script>
</head>

<body>
hello world
</body>

</html>
```

**Comment by masx200** [comment]
If you use jsdom, passing in an empty string will not report an error.

**Comment by WebReflection** [comment]
you don't need to parse if there's nothing to parse ... if you need a document create one via the *Document* ... I don't have use cases for this so I am not going to work on this. If you want to parse emptiness and you're happy with JSDOM use JSDOM, also because I don't think you gain any performance with empty strings here.
