### ISSUE TITLE
Error using Text constructor

### ISSUE THREAD

**Issue by UpperCod** [WebReflection/linkedom#78]
hi, i'm testing linkedom, but when using the `new Text` it throws an error.

## Code

```js
import { parseHTML } from "linkedom";

const browser = parseHTML(`
    <!doctype html>
    <html lang="en">
    </html>
`);


console.log(new browser.Text());

```

## Error

```
>node server.js

.../ssr/node_modules/linkedom/esm/shared/facades.js:16
  throw new TypeError('Illegal constructor');
        ^

TypeError: Illegal constructor
    at illegalConstructor (.../ssr/node_modules/linkedom/esm/shared/facades.js:16:9)
    at new Text (.../ssr/node_modules/linkedom/esm/shared/facades.js:51:26)
    at .../ssr/server/render.js:23:13
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

**Comment by WebReflection** [comment]
by design: https://github.com/WebReflection/linkedom/blob/main/esm/shared/facades.js#L51-L53

what's the use case for this? here every constructor needs a `document`, so use `document.createTextNode('')` instead?
