### ISSUE TITLE
insertBefore crashing unexpectedly

### ISSUE THREAD

**Issue by pkra** [WebReflection/linkedom#83]
This is a bit of a weird example which was reduced from slightly more complex DOM building (basically, populating & sorting a list)

```js
const { DOMParser } = require('linkedom');
const dom = (new DOMParser).parseFromString(``, 'text/html').defaultView;
const document = dom.window.document;
const div = document.createElement('div');
const span = document.createElement('span');
div.appendChild(span);
div.insertBefore(span, div.firstChild);
```
throws with the following:

```
/tmp/node_modules/linkedom/cjs/shared/utils.js:15
  prev[NEXT] = next;
             ^

TypeError: Cannot set property 'Symbol(next)' of null
    at knownAdjacent (/tmp/node_modules/linkedom/cjs/shared/utils.js:15:14)
    at knownBoundaries (/tmp/node_modules/linkedom/cjs/shared/utils.js:21:3)
    at EventTarget.insertBefore (/tmp/node_modules/linkedom/cjs/mixin/parent-node.js:219:9)
    at Object.<anonymous> (/tmp/linkedom_test.js:23:5)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by WebReflection** [comment]
You are inserting the span before itself ... but why don't you use a proper "*differ*" instead?

**Comment by WebReflection** [comment]
Btw, I see it doesn't throw on Web, maybe I should do nothing if the element is the same?

**Comment by pkra** [comment]
> You are inserting the span before itself ...

Yeah, this is an artificial example and it's not hard to work around on my end. 

> maybe I should do nothing if the element is the same?

I think that's the expected behavior, see https://dom.spec.whatwg.org/#concept-node-pre-insert.

**Comment by pkra** [comment]
Here's a side issue: when the elements arise from parsing, there's no crash but neither appendChild nor insertBefore work as expected.

```js
const { DOMParser } = require('linkedom');
const dom = (new DOMParser).parseFromString(`<!DOCTYPE html>
<html>
  <body><div></div><span></span></body>
</html>
`, 'text/html').defaultView;
const document = dom.window.document;
const div = document.querySelector('div');
const span = document.querySelector('span');
console.log(div.outerHTML, span.outerHTML) // <div></div> <span></span>
div.appendChild(span);
console.log(div.outerHTML); // <div></div> [DOM: <div><span></span></div>]
div.insertBefore(span, div.firstChild);
console.log(div.outerHTML); // <div></div> [DOM: <div><span></span></div>]
```

**Comment by WebReflection** [comment]
OK .. the `div.appendChild(span);` followed by `div.outerHTML` got me ... *that*, at least, shouldn't happen 👍

**Comment by pkra** [comment]
Sorry about that :innocent: I do suspect it's a separate issue though. In the original example,  after `appendChild` the `div.outerHTML` is ok.

**Comment by WebReflection** [comment]
I bet it is ... but I'll keep this as a bug regardless, as me bailing out if `node === before` is reasonable

**Comment by pkra** [comment]
Thank you, @WebReflection.
